language: python
python:
- 3.6.5
script:
  - make docs publish package
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "*.rpm"
    - "*.deb"
  skip_cleanup: true
  on:
    tags: true