language: python
python:
- 3.6.5
script:
  - pip install mkdocs mkdocs-material pymdown-extensions Pygments
  - git remote remove origin
  - git remote add origin "https://$GH_TOKEN@github.com/moshloop/ansible-deploy.git"
  - mkdocs gh-deploy