#!/bin/bash
target=ansible
inventory=
ARGS=
while getopts ":i:, :h, :t:" opt; do
  case $opt in
    h)
      echo "USAGE: ansible-deploy [any ansible-playbook arguments]"
      exit
      ;;
    t)
    target=$OPTARG
      ;;

    i)
    inventory=$OPTARG
      ;;

    \?)
      ARGS+="$ARGS $OPTARG"
      echo $ARGS $OPTARG $opt
      ;;
  esac
done


mkdir -p ~/.ansible/roles/
if [[ ! -e ~/.ansible/roles/deploy ]]; then
  git clone https://github.com/moshloop/ansible-deploy.git ~/.ansible/roles/deploy
fi

if [[ ! -e ~/.ansible/roles/extras ]]; then
  git clone https://github.com/moshloop/ansible-extras.git ~/.ansible/roles/extras
fi

cp ~/.ansible/roles/deploy/deploy.yml .ansible-deploy.yml
ansible-playbook .ansible-deploy.yml $@
