
- set_fact:
    _ports: []

- include: _ports.yml
  loop: "{{container.ports | default([]) }}"
  loop_control:
    loop_var: port

- name: Set container defaults
  set_fact:
    mem: "{{container.mem | default('1024') }}"
    cpu: "{{container.cpu | default('1') }}"
    volumes: "{{container.volumes | default([]) }}"
    files: "{{container.files | default(files) | default({}) }}"
    templates: "{{container.templates | default(templates) | default({})  }}"
    service: "{{container.service | default(container.image.split(':')[0]) | basename}}"
    env: "{{container.env | default(container.env_vars) | default(env_vars) | default({}) }}"
    labels: "{{container.labels | default(labels) | default({}) }}"
    commands: "{{container.commands | default(commands) | default([]) }}"

- set_fact:
    _container: "{{container | combine({'mem': mem, 'cpu': cpu, 'service': service, 'ports': _ports, 'volumes': volumes, 'files': files, 'templates': templates, 'env': env, 'labels': labels}) }}"

- set_fact:
    _containers: "{{_containers| default([]) + [_container]}}"
