- debug: msg="Parsing docker compose v3 {{item}}" verbosity=1

- include_vars:
    file: "{{item}}"
    name: services

- include: _parse_docker_compose_v3.yml
  with_dict: "{{services.services}}"
  loop_control:
    loop_var: svc