- set_fact:
    cluster_name: "{{cluster_name | default(envFull) }}"

- debug: var=containers verbosity=2

- shell: smarti k8s spec -i {{inventory_dir}} {{smarti_options | default('-v') }}
  check_mode: no
  register: smarti

- debug: msg="{{smarti.stderr | debug_obj}} {{smarti.rc}}"

- copy:
    dest: build/k8s.yml
    content: "{{smarti.stdout}}"
  check_mode: no

- name: Kustomize
  local_action: shell kustomize build k8s
  register: kustomize
  when: "'k8s/kustomization.yaml' | file_exists"
  tags:
    - kustomize
  failed_when: false

- set_fact:
    display: "{{ kustomize.stdout | default('') | debug_obj }}"
  when: kustomize.changed
  run_once: true
  tags:
    - kustomize

- fail:
    msg: "Kustomize failed: \n {{kustomize.stderr}}"
  when: kustomize.changed and kustomize.rc != 0
  tags:
    - kustomize

- file:
    path: "build/k8s.yml"
    content: "kustomize.stdout"
  when: kustomize.changed
  check_mode: no
  run_once: true
  tags:
    - kustomize

- name: Deploy specs to Kuberenetes
  local_action:  shell kubectl apply -f build/k8s.yml
  failed_when: false
  run_once: true
  register: deployment
  check_mode: no
  when: not ansible_check_mode


- set_fact:
    display: "{{ (deployment.stdout + deployment.stderr) | default('')  | debug_obj }}"
  when: deployment.changed

- fail: "{{deployment.stderr}}"
  when: deployment.changed and deployment.rc != 0

- name: Validate specs
  local_action:  shell kubectl apply -f build/k8s.yml --dry-run=true
  failed_when: false
  run_once: true
  register: deployment
  check_mode: no
  when: ansible_check_mode

- set_fact:
    display: "{{ (deployment.stdout + deployment.stderr) | default('')  | debug_obj }}"
  when: deployment.changed

- fail: "{{deployment.stderr}}"
  when: deployment.changed and deployment.rc != 0