  - debug: var=users verbosity=1
  - debug: var=commands verbosity=1
  - debug: var=volumes verbosity=1

  - file: path="{{inventory_dir}}/build/" state=directory

  - name: Installing systemd based docker services
    include_tasks: _container.yml
    with_items: "{{containers}}"
    loop_control:
      loop_var: container

  - name: rendering user-data for {{inventory_hostname}}
    local_action: template src="cloudinit.tpl" dest="{{inventory_dir}}/build/{{inventory_hostname}}.txt"
    when: os is not defined or os != 'coreos'

  - name: rendering user-data for {{inventory_hostname}}
    local_action: template src="coreos.tpl" dest="{{inventory_dir}}/build/{{inventory_hostname}}.txt"
    when: os is defined and os == 'coreos'


  - debug: msg="Creating cloudinit file {{inventory_dir}}/build/{{inventory_hostname}}.txt"